

GET http://localhost:7000/courses/published HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTdhMGJiZDJhMTY4NTI5YWRiMjJjMWYiLCJlbWFpbCI6Im56aXphb3NjYXIyNUBnbWFpbC5jb20iLCJpYXQiOjE3MDI0OTcyMTQsImV4cCI6MTcwMjU4MzYxNH0.V5fP1tVQNxPDFn-S-pQXJMq1A5_ZAgK1iyy2ORfFfWw

### signup

POST http://localhost:7000/auth/signup HTTP/1.1
Content-Type: application/json

{
    "username": "Oscar200",
    "fname":"Nziza",
    "lname":"Oscar",
    "email":"nzizaoscar25@gmail.com",
    "password":"oscar250140170"
   
}

### signout
GET  http://localhost:7000/auth/signout HTTP/1.1

### signin

POST http://localhost:7000/auth/signin HTTP/1.1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTdhMGJiZDJhMTY4NTI5YWRiMjJjMWYiLCJlbWFpbCI6Im56aXphb3NjYXIyNUBnbWFpbC5jb20iLCJpYXQiOjE3MDI0OTcyMTQsImV4cCI6MTcwMjU4MzYxNH0.V5fP1tVQNxPDFn-S-pQXJMq1A5_ZAgK1iyy2ORfFfWw

{
 "email":"nzizaoscar25@gmail.com",
 "password":"oscar250140170"

}



### CREATE COURSE userId= 657a0bbd2a168529adb22c1f

POST http://localhost:7000/courses/by/657a0bbd2a168529adb22c1f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTdhMGJiZDJhMTY4NTI5YWRiMjJjMWYiLCJlbWFpbCI6Im56aXphb3NjYXIyNUBnbWFpbC5jb20iLCJpYXQiOjE3MDI0OTcyMTQsImV4cCI6MTcwMjU4MzYxNH0.V5fP1tVQNxPDFn-S-pQXJMq1A5_ZAgK1iyy2ORfFfWw

{
 "name":"Testing",
 "description":"<p>Cloud Computing provides us a means by which we can access the applications as utilities, over the internet. It allows us to create, configure, and customize the business applications online.</p>",
 "image":"html5.png"
}

###_____________getCourse By instructor_________

GET  http://localhost:7000/courses/by/657a0bbd2a168529adb22c1f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTdhMGJiZDJhMTY4NTI5YWRiMjJjMWYiLCJlbWFpbCI6Im56aXphb3NjYXIyNUBnbWFpbC5jb20iLCJpYXQiOjE3MDI0OTcyMTQsImV4cCI6MTcwMjU4MzYxNH0.V5fP1tVQNxPDFn-S-pQXJMq1A5_ZAgK1iyy2ORfFfWw

### ___________________GET A COURSE_________________


GET http://localhost:7000/courses/a/657a19f9bf8b799245f856ab HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTdhMGJiZDJhMTY4NTI5YWRiMjJjMWYiLCJlbWFpbCI6Im56aXphb3NjYXIyNUBnbWFpbC5jb20iLCJpYXQiOjE3MDI0OTcyMTQsImV4cCI6MTcwMjU4MzYxNH0.V5fP1tVQNxPDFn-S-pQXJMq1A5_ZAgK1iyy2ORfFfWw


###____________________ADDING lESSONS TO COURSE

POST http://localhost:7000/courses/657a24b8aec410e93f1eda34/lesson/new HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTdhMGJiZDJhMTY4NTI5YWRiMjJjMWYiLCJlbWFpbCI6Im56aXphb3NjYXIyNUBnbWFpbC5jb20iLCJpYXQiOjE3MDI0OTcyMTQsImV4cCI6MTcwMjU4MzYxNH0.V5fP1tVQNxPDFn-S-pQXJMq1A5_ZAgK1iyy2ORfFfWw

{
"title":"Technologies",
"content":"<h2>Virtualization</h2><p><b>Virtualization</b> is a technique which allows to share single physical instance of an application or resource among multiple organizations or tenants(customers). It does so by assigning a logical name to a physical resource and providing a pointer to that physical resource when demanded.</p>",
"resourse_url":"https://www.javatpoint.com"
}

### ________________UPDATE COURSE___________________


PUT http://localhost:7000/courses/657a19f9bf8b799245f856ab HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTdhMGJiZDJhMTY4NTI5YWRiMjJjMWYiLCJlbWFpbCI6Im56aXphb3NjYXIyNUBnbWFpbC5jb20iLCJpYXQiOjE3MDI0OTcyMTQsImV4cCI6MTcwMjU4MzYxNH0.V5fP1tVQNxPDFn-S-pQXJMq1A5_ZAgK1iyy2ORfFfWw

{
  "name": "Cloud Computing",
  "published":true
  
}

### ________________DELETE COURSE_______________
DELETE  http://localhost:7000/courses/657a24b8aec410e93f1eda34 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTdhMGJiZDJhMTY4NTI5YWRiMjJjMWYiLCJlbWFpbCI6Im56aXphb3NjYXIyNUBnbWFpbC5jb20iLCJpYXQiOjE3MDI0OTcyMTQsImV4cCI6MTcwMjU4MzYxNH0.V5fP1tVQNxPDFn-S-pQXJMq1A5_ZAgK1iyy2ORfFfWw


###_________________PUBLISHED__COURSE_____________


GET http://localhost:7000/courses/published HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTdhMGJiZDJhMTY4NTI5YWRiMjJjMWYiLCJlbWFpbCI6Im56aXphb3NjYXIyNUBnbWFpbC5jb20iLCJpYXQiOjE3MDI0OTcyMTQsImV4cCI6MTcwMjU4MzYxNH0.V5fP1tVQNxPDFn-S-pQXJMq1A5_ZAgK1iyy2ORfFfWw




###__________________________Update profile info
PUT  http://localhost:7000/user/657a0bbd2a168529adb22c1f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTdhMGJiZDJhMTY4NTI5YWRiMjJjMWYiLCJlbWFpbCI6Im56aXphb3NjYXIyNUBnbWFpbC5jb20iLCJpYXQiOjE3MDI0OTcyMTQsImV4cCI6MTcwMjU4MzYxNH0.V5fP1tVQNxPDFn-S-pQXJMq1A5_ZAgK1iyy2ORfFfWw

{
    "username": "Oscar200",
    "fname":"Nziza",
    "lname":"Oscar",
    "email":"nzizaoscar25@gmail.com",
    "password":"oscar250140170",
    "about":"A passionate Software Engineer",
    "educator":true

   
}



