[build]
  command = "npm install "
  functions = "."  
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]


[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"


