[build]
  command = "npm install "
  functions = "."  

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/server"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

